using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class README : MonoBehaviour {


	// FROM TIME TO TIME THERE IS A STRANGE BUG THAT OCCURS ONLY WHEN THE GAME VIEW INS'T MAXIMISED ! 

	// SO IF YOU DO GET SOME RED ERRORS, JUST MAXIMISE ON PLAY AND THINGS SHOULD WORK SMOOTHLY !

	// OF COURSE THESE ERRORS WILL NOT EFFECT THE GAME ONCE IT HAS BEEN BUILT AND LAUNCHED :) !

	// IF YOU ENCOUNTER ANY OTHER BUG TELL ME SO VIA DISCORD (LINK IN THE DESCRIPTION :) ) !
		
}
